"""initial setup

Revision ID: 4edac1476802
Revises: 
Create Date: 2025-06-13 13:06:49.725706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edac1476802'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_authors'))
    )
    with op.batch_alter_table('blog_authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_authors_name'), ['name'], unique=False)

    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_id'), ['id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=True)

    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('name', name=op.f('uq_manufacturers_name'))
    )
    op.create_table('blog_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_blog_users_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_users'))
    )
    with op.batch_alter_table('blog_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_users_customer_id'), ['customer_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_timestamp'), ['timestamp'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_products_manufacturer_id_manufacturers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_manufacturer_id'), ['manufacturer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_year'), ['year'], unique=False)

    op.create_table('blog_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('translation_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], name=op.f('fk_blog_articles_author_id_blog_authors')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_blog_articles_language_id_languages')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_blog_articles_product_id_products')),
    sa.ForeignKeyConstraint(['translation_of_id'], ['blog_articles.id'], name=op.f('fk_blog_articles_translation_of_id_blog_articles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_articles'))
    )
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_articles_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_translation_of_id'), ['translation_of_id'], unique=False)

    op.create_table('blog_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['blog_users.id'], name=op.f('fk_blog_sessions_user_id_blog_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_sessions'))
    )
    with op.batch_alter_table('blog_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('orders_items',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_orders_items_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_items_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'order_id', name=op.f('pk_orders_items'))
    )
    with op.batch_alter_table('orders_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_items_product_id'), ['product_id'], unique=False)

    op.create_table('product_countries',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_product_countries_country_id_countries')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_countries_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'country_id', name=op.f('pk_product_countries'))
    )
    op.create_table('products_reviews',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_products_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_products_reviews_product_id_products')),
    sa.PrimaryKeyConstraint('customer_id', 'product_id', name=op.f('pk_products_reviews'))
    )
    with op.batch_alter_table('products_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_reviews_timestamp'), ['timestamp'], unique=False)

    op.create_table('blog_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['blog_articles.id'], name=op.f('fk_blog_views_article_id_blog_articles')),
    sa.ForeignKeyConstraint(['session_id'], ['blog_sessions.id'], name=op.f('fk_blog_views_session_id_blog_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_views'))
    )
    with op.batch_alter_table('blog_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_views_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_views_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_views_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_views_timestamp'))
        batch_op.drop_index(batch_op.f('ix_blog_views_session_id'))
        batch_op.drop_index(batch_op.f('ix_blog_views_article_id'))

    op.drop_table('blog_views')
    with op.batch_alter_table('products_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_reviews_timestamp'))

    op.drop_table('products_reviews')
    op.drop_table('product_countries')
    with op.batch_alter_table('orders_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_orders_items_order_id'))

    op.drop_table('orders_items')
    with op.batch_alter_table('blog_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_sessions_user_id'))

    op.drop_table('blog_sessions')
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_articles_translation_of_id'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_title'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_timestamp'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_product_id'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_language_id'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_author_id'))

    op.drop_table('blog_articles')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_year'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_manufacturer_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_timestamp'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('blog_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_users_customer_id'))

    op.drop_table('blog_users')
    op.drop_table('manufacturers')
    op.drop_table('languages')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))

    op.drop_table('customers')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_id'))

    op.drop_table('countries')
    with op.batch_alter_table('blog_authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_authors_name'))

    op.drop_table('blog_authors')
    # ### end Alembic commands ###
